import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Constants } from "@/lib/constants";
import HeaderComponent from "@/components/Layout/Header";
import { Toaster } from "@/components/ui/sonner";
import { EventProvider } from "./_providers/events-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: Constants.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-full">
          <HeaderComponent />
          <EventProvider>
            <section className="pt-16 h-full items-center">{children}</section>
          </EventProvider>
          <Toaster />
        </main>
      </body>
    </html>
  );
}
